FROM registry.access.redhat.com/openshift3/ose

MAINTAINER simontim <simone.mastrodonato@telecomitalia.it>

EXPOSE 4444 5555

RUN yum update -y

#installi browser display e driver
#scarichi selenium server 3.81
assegni i permessi al'utente 1001
USER 1001
#lanci il server con il display davanti
CMD[ ... ]
